name: FE CI

on:
  push:
    branches:
      - 'releases/**'
      - 'main'
      - 'master'
    paths:
      - 'containers/**'
      - 'scope/**'
      - 'src/**'
      - 'upload/**'

jobs:
  build_dashboard:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 8

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 14.x
        
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Aliyun Container Registry (ACR)
      uses: docker/login-action@v2
      with:
        registry: https://registry.us-west-1.aliyuncs.com
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
        
    - name: Build And Push Docker Image
      shell: bash
      run: |
          set -o xtrace
          branch="${GITHUB_REF#refs/heads/}"
          timestamp=`TZ="Asia/Shanghai" date +"%Y%m%d%H%M%S"`
          export VERSION="$branch-$timestamp-solo"
          export ARCH=all
          export REGISTRY=registry.us-west-1.aliyuncs.com/yunion-dev
          make image
